tests/mypy/mypy_function_wrapper_cls_t4.py:24: error: Argument 2 to "FunctionWrapper" has incompatible type "Callable[[Any], Any]"; expected "Callable[[Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[type[Any], Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str] | Callable[[Any, Callable[[int, str], str], Any, tuple[Any, ...], dict[str, Any]], str]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
